### ISSUE TITLE
All windows are pure black

### ISSUE THREAD

**Issue by SomeTitanicFan** [ManuEcheveste/PizzaTimer#2]
Hello, and sorry to bother you.

When I try to run Pizza Timer on my device, the windows appear, but are just black boxes I cannot do anything with. They still play Meatophobia, intrestingly enough, but aside from that, nothing happens.

I am using the latest version of Pizza Timer on a HP Laptop runing Windows 10, if that information is needed.

![Screenshot (156)](https://github.com/ManuEcheveste/PizzaTimer/assets/169209806/7a103c28-b9a8-42b9-9a44-cc8d5e3c7ca6)

**Comment by SomeTitanicFan** [comment]
I have come to the discovery that the timer still works, but it's just that the sprites are not loading.

**Comment by ManuEcheveste** [comment]
Hi, thank you for taking the time to create this report. It's not a bother at all! You help me make Pizza Timer better for everyone.
It's weird that the sprites aren't loading. You're sure that everything else works? Can you still, for example, click John pillar to start the timer? (that's the impression I got from your second comment).
Please, if you would be so kind, could you kindly tell me what are the specs of your computer?
How much RAM does your PC have, what's the CPU, and the integrated GPU specs. You can open the Task Manager and click the performance tab to see this information.
And also, just to be sure, try downloading the game once more, and hopefully the issue was a bad download.

**Comment by SomeTitanicFan** [comment]
Yes, everything else still functions. Pizza Time can still be activated, but no sprites load.

CPU: Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
RAM: 8.0 GB
GPU: Intel(R) HD Graphics 620

The issue persists after reinstalling Pizza Timer, strangely enough.

**Comment by ManuEcheveste** [comment]
That's weird. Maybe it's an issue with the graphic drivers, or maybe Pizza Timer it's too heavy for your computer. Will try to release an update today that hopefully fixes this issue.

**Comment by ManuEcheveste** [comment]
Update took longer, but tried to fix this issue. Please download the latest version from [itch.io](https://manuecheveste.itch.io/pizza-timer) and let me know if the issue was fixed.

**Comment by SomeTitanicFan** [comment]
The issue has been resolved, thank you so much!
